feat: add support vue build

diff --git a/actions/docker-tmp-image-build/action.yml b/actions/docker-tmp-image-build/action.yml
--- a/actions/docker-tmp-image-build/action.yml
+++ b/actions/docker-tmp-image-build/action.yml
@@ -6,6 +6,14 @@ inputs:
   image_repository:
     description: Path to docker image repository
     required: true
+  app_type:
+    description: Type Application with select build environments
+    required: false
+    default: "spring"
+  environment:
+    description: Environment with application, if required
+    required: false
+    default: ""
 
 outputs:
   default_docker_image:
@@ -16,6 +24,7 @@ runs:
   using: composite
   steps:
     - name: Gradle cache
+      if: ${{ inputs.app_type == 'spring' }}
       uses: actions/cache@v5
       with:
         path: |
@@ -25,13 +34,32 @@ runs:
         restore-keys: |
           ${{ runner.os }}-gradle-
     - name: Setup JDK 21
+      if: ${{ inputs.app_type == 'spring' }}
       uses: actions/setup-java@v5
       with:
         distribution: temurin
         java-version: 21
     - name: Build app jar
+      if: ${{ inputs.app_type == 'spring' }}
       shell: bash
       run: ./gradlew clean build -x test
+    - name: Setup Node.js
+      if: ${{ inputs.app_type == 'vue' }}
+      uses: actions/setup-node@v5
+      with:
+        node-version: 20
+    - name: Build
+      if: ${{ inputs.app_type == 'vue' }}
+      shell: bash
+      run: |
+        set -e
+        ENV="${{ inputs.environment }}"
+        if [[ -z "$ENV" ]]; then
+          echo "With VUE APP Environment is required. Environment is required. Available: dev, prod, staging"
+          exit 1
+        fi
+        npm ci
+        npm run build:${{ inputs.environment }}
     - name: Create docker default tag
       shell: bash
       id: docker-tag
